application: banter-ventures
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /media
  static_dir: media
- url: /data
  static_dir: data
  application_readable: true
- url: /.*
  script: app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
